# Generated by Django 4.2.3 on 2023-07-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PendingUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("phone", models.CharField(max_length=20)),
                (
                    "verification_code",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                ("password", models.CharField(max_length=255, null=True)),
            ],
            options={"abstract": False,},
        ),
    ]
